[package]
rust-version.workspace = true
name = "sdkwork-api-agents-standalone-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "SDKWork Agents runnable HTTP API server"


[lints]
workspace = true
[lib]
name = "sdkwork_api_agents_standalone_gateway"
path = "src/lib.rs"

[[bin]]
name = "sdkwork-api-agents-standalone-gateway"
path = "src/main.rs"

[dependencies]
sdkwork-api-agents-assembly.workspace = true
sdkwork-iam-web-adapter.workspace = true
sdkwork-web-bootstrap.workspace = true
axum.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
if-addrs.workspace = true
