[package]
name = "sdkwork-api-agents-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-agents application HTTP plane."

[lib]
name = "sdkwork_api_agents_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
anyhow.workspace = true
sdkwork-agent-server.workspace = true
sdkwork-agents-kernel-bridge.workspace = true
sdkwork-agents-database-host.workspace = true
sdkwork-agents-runtime-facade.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-intelligence-agents-service.workspace = true
sdkwork-web-contract.workspace = true
sdkwork-iam-database-host.workspace = true
sdkwork-iam-embedded-application-bootstrap.workspace = true
sdkwork-iam-web-adapter.workspace = true
sdkwork-routes-iam-app-api.workspace = true
sdkwork-api-assets-assembly.workspace = true
sdkwork-api-drive-assembly.workspace = true
sdkwork-routes-drive-app-api.workspace = true
sdkwork-routes-agents-http-shared.workspace = true
serde_json.workspace = true
sdkwork-api-generations-assembly.workspace = true
sdkwork-routes-agents-app-api.workspace = true
sdkwork-routes-agents-backend-api.workspace = true
sdkwork-routes-agents-open-api.workspace = true
