[package]
rust-version.workspace = true
name = "sdkwork-agents-integration-tests"
version.workspace = true
edition.workspace = true
publish = false


[lints]
workspace = true
[dev-dependencies]
axum.workspace = true
http.workspace = true
tokio.workspace = true
tower.workspace = true
sdkwork-agents-contract.workspace = true
sdkwork-api-agents-standalone-gateway.workspace = true
sdkwork-api-agents-assembly.workspace = true
