environment = "test"

[http]

[http.certificates]

[http.certificates."sdkwork.com"]
certFile = "/opt/certs/letsencrypt/live/sdkwork.com/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/sdkwork.com/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/sdkwork.com/chain.pem"
ocspStapling = true

[http.certificates."birdcoder.com"]
certFile = "/opt/certs/letsencrypt/live/birdcoder.com/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/birdcoder.com/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/birdcoder.com/chain.pem"
ocspStapling = true

[http.certificates."dtupay.com"]
certFile = "/opt/certs/letsencrypt/live/dtupay.com/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/dtupay.com/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/dtupay.com/chain.pem"
ocspStapling = true

[http.certificates."sdkwork.cn"]
certFile = "/opt/certs/letsencrypt/live/sdkwork.cn/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/sdkwork.cn/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/sdkwork.cn/chain.pem"
ocspStapling = true

[http.certificates."birdcoder.cn"]
certFile = "/opt/certs/letsencrypt/live/birdcoder.cn/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/birdcoder.cn/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/birdcoder.cn/chain.pem"
ocspStapling = true

[http.certificates."dtupay.cn"]
certFile = "/opt/certs/letsencrypt/live/dtupay.cn/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/dtupay.cn/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/dtupay.cn/chain.pem"
ocspStapling = true

[[http.server]]
listen = ["80"]
serverName = ["agents-test.sdkwork.com", "agents-test.birdcoder.com", "agents-test.dtupay.com", "agents-test.sdkwork.cn", "agents-test.birdcoder.cn", "agents-test.dtupay.cn", "agents-app-test.sdkwork.com", "agents-app-test.birdcoder.com", "agents-app-test.dtupay.com", "agents-app-test.sdkwork.cn", "agents-app-test.birdcoder.cn", "agents-app-test.dtupay.cn", "agents-admin-test.sdkwork.com", "agents-admin-test.birdcoder.com", "agents-admin-test.dtupay.com", "agents-admin-test.sdkwork.cn", "agents-admin-test.birdcoder.cn", "agents-admin-test.dtupay.cn", "agents-open-test.sdkwork.com", "agents-open-test.birdcoder.com", "agents-open-test.dtupay.com", "agents-open-test.sdkwork.cn", "agents-open-test.birdcoder.cn", "agents-open-test.dtupay.cn"]

[[http.server.location]]
match = "/api/"
proxyPass = "http://gateway"
proxyHttpVersion = "1.1"
proxySetHeader = ["Host $host", "X-Forwarded-For $proxy_add_x_forwarded_for", "X-Forwarded-Proto $scheme"]

[[http.server.location]]
match = "/"
proxyPass = "http://gateway"
proxyHttpVersion = "1.1"
proxySetHeader = ["Host $host", "X-Forwarded-For $proxy_add_x_forwarded_for", "X-Forwarded-Proto $scheme"]
proxyBuffering = false
proxyReadTimeout = "300s"

